controller_manager:
  ros__parameters:
    update_rate: 100 # dalam hz

    joint_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"
    
    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"

joint_trajectory_controller:
  ros__parameters:
    joints:
      - Base_Coxa
      - Coxa_Femur
      - Femur_Tibia
    command_interfaces:
      - position
    state_interfaces:
      - position

joint_state_broadcaster:
  ros__parameters:
    joints: 
      - Base_Coxa
      - Coxa_Femur
      - Femur_Tibia